---
id: eslint-config
version: 1.0.0
category: quality
description: ESLint configuration for JavaScript/TypeScript projects
language: javascript
dependencies: ["eslint"]
variables:
  - name: TYPESCRIPT_SUPPORT
    description: Enable TypeScript support (true/false)
    required: false
    default: "false"
---

// ESLint configuration
// Generated by Project Catalyst

module.exports = {
  env: {
    node: true,
    es2022: true,
  },
  extends: [
    'eslint:recommended',
    ${TYPESCRIPT_SUPPORT === 'true' ? "'plugin:@typescript-eslint/recommended'," : ""}
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
    // Possible Errors
    'no-console': 'warn',
    'no-debugger': 'error',

    // Best Practices
    'eqeqeq': ['error', 'always'],
    'no-var': 'error',
    'prefer-const': 'error',
    'prefer-arrow-callback': 'warn',

    // Style
    'indent': ['error', 2],
    'quotes': ['error', 'single'],
    'semi': ['error', 'always'],
    'comma-dangle': ['error', 'always-multiline'],

    // ES6+
    'arrow-spacing': 'error',
    'no-duplicate-imports': 'error',
  },
  ignorePatterns: [
    'node_modules/',
    'dist/',
    'build/',
    'coverage/',
  ],
};
